import PDFDocument from 'pdfkit';
import fs from 'fs';
import Database from 'better-sqlite3';

const SEVERITY_COLORS: Record<string, string> = {
  critical: '#ef4444',
  high: '#f97316',
  medium: '#eab308',
  low: '#3b82f6',
  info: '#6b7280',
};

export function generatePdfReport(db: Database.Database, scanId: string, outputPath: string): void {
  const scan = db.prepare('SELECT * FROM scans WHERE id = ?').get(scanId) as any;
  if (!scan) throw new Error('Scan not found');

  const findings = db.prepare('SELECT * FROM findings WHERE scan_id = ? ORDER BY cvss_score DESC').all(scanId) as any[];
  const counts = JSON.parse(scan.findings_count || '{}');

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = fs.createWriteStream(outputPath);
  doc.pipe(stream);

  // Title Page
  doc.fontSize(28).fillColor('#00ff88').text('HackMe', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(16).fillColor('#666').text('Security Scan Report', { align: 'center' });
  doc.moveDown(2);

  doc.fontSize(11).fillColor('#333');
  doc.text(`Target: ${scan.target_url}`);
  doc.text(`Profile: ${scan.profile}`);
  doc.text(`Date: ${new Date(scan.started_at || scan.completed_at || Date.now()).toLocaleString()}`);
  doc.text(`Total Requests: ${scan.total_requests}`);
  doc.text(`Total Findings: ${findings.length}`);
  doc.moveDown();

  // Summary Table
  doc.fontSize(14).fillColor('#000').text('Severity Summary');
  doc.moveDown(0.5);
  for (const [sev, count] of Object.entries(counts)) {
    doc.fontSize(10).fillColor(SEVERITY_COLORS[sev] || '#333').text(`  ${sev.toUpperCase()}: ${count}`, { continued: false });
  }
  doc.moveDown();

  // Findings
  doc.addPage();
  doc.fontSize(14).fillColor('#000').text('Findings Detail');
  doc.moveDown();

  for (const finding of findings) {
    if (doc.y > 680) doc.addPage();

    doc.fontSize(11).fillColor(SEVERITY_COLORS[finding.severity] || '#333')
      .text(`[${finding.severity.toUpperCase()}] ${finding.title}`);
    doc.fontSize(9).fillColor('#555')
      .text(`URL: ${finding.url || 'N/A'}`);

    if (finding.parameter) {
      doc.text(`Parameter: ${finding.parameter}`);
    }
    if (finding.cwe_id) {
      doc.text(`CWE: ${finding.cwe_id} | OWASP: ${finding.owasp_category || 'N/A'} | CVSS: ${finding.cvss_score || 'N/A'}`);
    }

    doc.moveDown(0.3);
    doc.fontSize(9).fillColor('#333').text(finding.description || '', { width: 500 });
    doc.moveDown(0.3);

    if (finding.remediation) {
      doc.fontSize(9).fillColor('#0066cc').text(`Remediation: ${finding.remediation}`, { width: 500 });
    }

    doc.moveDown(0.5);
    doc.strokeColor('#ddd').moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);
  }

  // Footer
  doc.fontSize(8).fillColor('#999').text(
    `Generated by HackMe Security Scanner — ${new Date().toISOString()}`,
    50, doc.page.height - 40, { align: 'center' }
  );

  doc.end();
}
