export const OWASP_2021: Record<string, string> = {
  'A01:2021': 'Broken Access Control',
  'A02:2021': 'Cryptographic Failures',
  'A03:2021': 'Injection',
  'A04:2021': 'Insecure Design',
  'A05:2021': 'Security Misconfiguration',
  'A06:2021': 'Vulnerable and Outdated Components',
  'A07:2021': 'Identification and Authentication Failures',
  'A08:2021': 'Software and Data Integrity Failures',
  'A09:2021': 'Security Logging and Monitoring Failures',
  'A10:2021': 'Server-Side Request Forgery',
};

export const CWE_MAP: Record<string, string> = {
  'CWE-79': 'Cross-site Scripting (XSS)',
  'CWE-89': 'SQL Injection',
  'CWE-78': 'OS Command Injection',
  'CWE-94': 'Code Injection',
  'CWE-918': 'Server-Side Request Forgery (SSRF)',
  'CWE-611': 'XML External Entity (XXE)',
  'CWE-352': 'Cross-Site Request Forgery (CSRF)',
  'CWE-22': 'Path Traversal',
  'CWE-287': 'Improper Authentication',
  'CWE-862': 'Missing Authorization',
  'CWE-639': 'Insecure Direct Object Reference (IDOR)',
  'CWE-200': 'Information Exposure',
  'CWE-16': 'Configuration',
  'CWE-295': 'Improper Certificate Validation',
  'CWE-327': 'Use of Broken Crypto Algorithm',
  'CWE-346': 'Origin Validation Error',
  'CWE-601': 'Open Redirect',
  'CWE-434': 'Unrestricted File Upload',
  'CWE-502': 'Deserialization of Untrusted Data',
  'CWE-1321': 'Prototype Pollution',
  'CWE-444': 'HTTP Request Smuggling',
  'CWE-525': 'Information Exposure Through Browser Caching',
};
